### ISSUE TITLE
Error running on PHP 7.0

### ISSUE THREAD

**Issue by jalendport** [TopShelfCraft/Environment-Label#1]
The `void` return type was [introduced](https://wiki.php.net/rfc/void_return_type) in PHP 7.1 so installing Environment-Label while running PHP 7.0 results in the following error: `Return value of topshelfcraft\environmentlabel\services\Label::doItBaby() must be an instance of topshelfcraft\environmentlabel\services\void, none returned`.

https://github.com/TopShelfCraft/Environment-Label/blob/5830dd90f70f94ed6fc74a4741c93a1236e58616/src/services/Label.php#L160-L165

**Comment by michaelrog** [comment]
Since the Readme claims that _Environment Label_ works with PHP 7.0, I'm gonna call this a Bug: We should do away with the offending type-hint.
