### ISSUE TITLE
Undefined constant "TopShelfCraft\EnvironmentLabel\CRAFT_ENVIRONMENT"

### ISSUE THREAD

**Issue by skeemer** [TopShelfCraft/Environment-Label#12]
As soon as I install the plugin, either by CLI or GUI, I get this error.

```
Error: Undefined constant "TopShelfCraft\EnvironmentLabel\CRAFT_ENVIRONMENT" in /Users/skeemer/Sites/website/vendor/topshelfcraft/environment-label/src/EnvironmentLabel.php:56
Stack trace:
#0 /Users/skeemer/Sites/website/vendor/craftcms/cms/src/base/Plugin.php(177): TopShelfCraft\EnvironmentLabel\EnvironmentLabel->createSettingsModel()
#1 /Users/skeemer/Sites/website/vendor/topshelfcraft/environment-label/src/Label.php(112): craft\base\Plugin->getSettings()
#2 /Users/skeemer/Sites/website/vendor/topshelfcraft/environment-label/src/EnvironmentLabel.php(45): TopShelfCraft\EnvironmentLabel\Label->doItBaby()
#3 [internal function]: TopShelfCraft\EnvironmentLabel\EnvironmentLabel->TopShelfCraft\EnvironmentLabel\{closure}(Object(craft\events\TemplateEvent))
#4 /Users/skeemer/Sites/website/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\TemplateEvent))
#5 /Users/skeemer/Sites/website/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\web\\View', 'beforeRenderPag...', Object(craft\events\TemplateEvent))
#6 /Users/skeemer/Sites/website/vendor/craftcms/cms/src/web/View.php(1830): yii\base\Component->trigger('beforeRenderPag...', Object(craft\events\TemplateEvent))
#7 /Users/skeemer/Sites/website/vendor/craftcms/cms/src/web/View.php(452): craft\web\View->beforeRenderPageTemplate('blog/index.twig', Array, 'site')
#8 /Users/skeemer/Sites/website/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate('blog/index.twig', Array, 'site')
#9 /Users/skeemer/Sites/website/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#10 /Users/skeemer/Sites/website/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#11 /Users/skeemer/Sites/website/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#12 /Users/skeemer/Sites/website/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#13 /Users/skeemer/Sites/website/web/index.php(12): yii\base\Application->run()
#14 /Users/skeemer/.composer/vendor/laravel/valet/server.php(234): require('/Users/skeemer/...')
#15 {main}
```

This is Craft 4.0.4 and topshelfcraft/environment-label 4.0.0.

**Comment by michaelrog** [comment]
Please make sure you have the [`CRAFT_ENVIRONMENT`](https://craftcms.com/docs/4.x/config/#craft-environment) constant defined in your application index file.

**Comment by petenice** [comment]
In Craft3 I have CRAFT_ENVIRONMENT defined in the .env file, is it different in Craft4 ? 

CRAFT_ENVIRONMENT=dev

**Comment by skeemer** [comment]
I checked an older Craft 3 project and found this in `bootstrap.php`, at the end. (I think in that file vs. index.php is preferred.)
```
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
```

I ended up setting this to not break possible deployment compatibility.
```
define('CRAFT_ENVIRONMENT', getenv('CRAFT_ENVIRONMENT') ?: getenv('ENVIRONMENT') ?: 'production');
```

There was nothing like this in the default Craft 4 install, so something probably needs added to the docs.

**Comment by petenice** [comment]
Thanks, I'm looking at the [Craft4 docs](https://craftcms.com/docs/4.x/config/#craft-environment)

"Prior to Craft 4, craftcms/craft projects had CRAFT_ENVIRONMENT fall back to a value of production by default. This is no longer the case, as the default is [explicitly set to dev](https://github.com/craftcms/craft/blob/main/.env.example#L5)"

**Comment by skeemer** [comment]
The problem isn't regarding the .env file or environment variable , but that by default, there is no code that sets that as a constant.

**Comment by petenice** [comment]
Thanks, so then without making changes to the Craft4 default install, this add-on won't work. I appreciate your insight and assistance.

**Comment by michaelrog** [comment]
I see that the Craft 4 starter project removed those constant assignments. I'll update the plugin so it doesn't rely on `CRAFT_ENVIRONMENT` being set by default.

(You can resolve your immediate issue simply by defining the `CRAFT_ENVIRONMENT` constant in your `index.php`.)

**Comment by Joobs** [comment]
@michaelrog I just made a new Craft Starter project and the issue is still there.

Following the suggestion by skeemer I added this to `web/index.php`

```
define('CRAFT_ENVIRONMENT', getenv('CRAFT_ENVIRONMENT') ?: getenv('ENVIRONMENT') ?: 'production');
```

**Comment by michaelrog** [comment]
@Joobs The plugin no longer uses `CRAFT_ENVIRONMENT` as a default, as of [4.0.1](https://github.com/TopShelfCraft/Environment-Label/blob/master/CHANGELOG.md#401---2022-07-11), so this should no longer be an issue. 😄

**Comment by Joobs** [comment]
@michaelrog I think it needs to be updated somewhere else, the JS global references the `CRAFT_ENVIRONMENT` constant.

```
Error

Undefined constant "TopShelfCraft\EnvironmentLabel\CRAFT_ENVIRONMENT"

1. in /var/www/html/vendor/topshelfcraft/environment-label/src/Label.php at line 97
```

``` 
    /**
     * @return string
     */
    public function getJs(): string
    {
 
        $js = "window.CRAFT_ENVIRONMENT = " . json_encode(CRAFT_ENVIRONMENT) . ";";
 
        $props = get_object_vars(EnvironmentLabel::getInstance()->getSettings());
        $props['renderedText'] = $this->getRenderedText();
        $js .= "window.CRAFT_ENVIRONMENT_LABEL = " . json_encode($props) . ";";
 
        return $js;
 
    }
 ```

**Comment by michaelrog** [comment]
Doh. Can't believe I overlooked that. Thanks. Re-opening this and will push a fix momentarily.

**Comment by michaelrog** [comment]
`4.0.2` is out now with this fix. Thanks yall!

**Comment by samueldraper** [comment]
@michaelrog I installed 4.0.2 but it sill can't find the constant regardless of whether I add @Joobs suggestion into web/index.php or not.

**Comment by michaelrog** [comment]
@samueldraper What error message are you seeing now?

**Comment by Joobs** [comment]
@samueldraper 4.0.2 no longer looks for the constant `CRAFT_ENVIRONMENT` in `index.php`. (my index.php no longer includes that)

Make sure in your `.env` file you have `CRAFT_ENVIRONMENT=dev` (or staging, production etc)

**Comment by michaelrog** [comment]
The plugin no longer assumes `CRAFT_ENVIRONMENT` is defined anywhere — constant _or_ `.env`.

If you define a `CRAFT_ENVIRONMENT` _constant_ (in your `index.php`), _and_ you don't provide a `labelText` in the settings, _then_ the label will fall back to the constant value.

If you want to use a `.env` var, you'd need to specifically reference that from your config file. (Just adding `CRAFT_ENVIRONMENT` to your `.env` won't have any effect unless you explicitly fetch that value from the settings.)

**Comment by samueldraper** [comment]
> The plugin no longer assumes `CRAFT_ENVIRONMENT` is defined anywhere — constant _or_ `.env`.
> 
> If you define a `CRAFT_ENVIRONMENT` _constant_ (in your `index.php`), _and_ you don't provide a `labelText` in the settings, _then_ the label will fall back to the constant value.
> 
> If you want to use a `.env` var, you'd need to specifically reference that from your config file. (Just adding `CRAFT_ENVIRONMENT` to your `.env` won't have any effect unless you explicitly fetch that value from the settings.)

Does that mean that in any case, CRAFT_ENVIRONMENT must be defined? That's working.
Because the standard install without creating a config file does not display any default label.

Also, if the bg colour is changed within the control panel, it does not show up. The CSS added to the page seems to omit the # before the hex color code (only if changed from default).

**Comment by michaelrog** [comment]
> Does that mean that in any case, CRAFT_ENVIRONMENT must be defined?

No — `CRAFT_ENVIRONMENT` does not need to be defined.

> Because the standard install without creating a config file does not display any default label.

That is the expected behavior for now. You can set the label text via the settings or in the config.

(Or, optionally, you can define a `CRAFT_ENVIRONMENT` constant as a fallback. This provides for backwards compatibility with Craft 3 projects.)

> Also, if the bg colour is changed within the control panel, it does not show up. The CSS added to the page seems to omit the # before the hex color code (only if changed from default).

Happy to investigate — Please open a new issue for this.
