### ISSUE TITLE
Getting Error on Install

### ISSUE THREAD

**Issue by brianrivet-tilt** [TopShelfCraft/Environment-Label#13]
Hi,

I just tried to install v.4.0.0 on Craft 4.1.0 and as soon as it runs the install, when the screen refreshes it is an error screen saying:

Undefined constant "TopShelfCraft\EnvironmentLabel\CRAFT_ENVIRONMENT"

I was able to uninstall via the command line, but would like to be able to use the plugin as I've used it on all my sites in the past.

Thanks!

Brian

**Comment by michaelrog** [comment]
Fixed in b909586, released as 4.0.1.
