### ISSUE TITLE
Undefined constant "TopShelfCraft\EnvironmentLabel\CRAFT_ENVIRONMENT"

### ISSUE THREAD

**Issue by jakelapan** [TopShelfCraft/Environment-Label#14]
Out of the box I get the following error with installing Environment Label on a Craft 4 project:

`Undefined constant "TopShelfCraft\EnvironmentLabel\CRAFT_ENVIRONMENT"`

Here are my Craft project specs:
- PHP 8.1.8
- MySQL 8.0.29
- Craft Pro 4.2.0.2

**Comment by michaelrog** [comment]
c.f. #12 — will push a fix momentarily.

**Comment by michaelrog** [comment]
`4.0.2` is out now with this fix. Thanks @jakelapan!

**Comment by jakelapan** [comment]
Awesome! Much appreciated :)
