### ISSUE TITLE
CP settings strip the # from hex colours and breaks the styles

### ISSUE THREAD

**Issue by uandco** [TopShelfCraft/Environment-Label#15]
Setting this:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/26996169/201000451-c4eb6387-a079-4a6b-af13-cb093ef5da05.png">

Produces this:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/26996169/201000426-e070448f-7659-4767-bd8f-804cfa614df1.png">

Editing the `environment-label` section of `project.yaml` and applying the changes fixes the issue.

**Comment by michaelrog** [comment]
Thanks Thibaut — maybe a change in the Color field... I'll take a look!

**Comment by uandco** [comment]
No worries, sorry I forgot to mention I'm using Craft Pro 4.3.1

**Comment by sander-lameco** [comment]
Came here with the exact same issue, setting the color via the `config/environment-label.php` file works but isn't preferred. Any update on it @michaelrog, currently on `4.4.7.1` of Craft

**Comment by michaelrog** [comment]
This is fixed in `4.0.3`. Thanks yall!
