### ISSUE TITLE
labelText may not include ' because that breaks the CSS 

### ISSUE THREAD

**Issue by d--j** [TopShelfCraft/Environment-Label#16]
The labelText gets inserted as is in the generated CSS. If the labelText includes a `'` this breaks the CSS.

https://github.com/TopShelfCraft/Environment-Label/blob/9311bd50df251bfadb6f421646bee2fb85e593c4/src/Label.php#L75

You should escape the rendered text before inseting it into the page. E.g. use this code (copied from Twig):
```php
            $renderedText = preg_replace_callback('#[^a-zA-Z0-9]#Su', function ($matches) {
                $char = $matches[0];

                return sprintf('\\%X ', 1 === \strlen($char) ? \ord($char) : mb_ord($char, 'UTF-8'));
            }, $renderedText);
```

**Comment by michaelrog** [comment]
Thanks for bringing this up. I'm sympathetic to this issue. This plugin is a developer tool, and I'm inclined to lean on developers to enforce valid label text on their own. But, I'll give it some more thought...

**Comment by michaelrog** [comment]
Upon reflection — and running into this annoyance in my own docs example 😆 — I went ahead and ran the label text through `addslashes()` for some light escaping.

This is out now in `5.0.0`.
