### ISSUE TITLE
Craft 5 compatibility

### ISSUE THREAD

**Issue by russback** [TopShelfCraft/Environment-Label#17]
With Craft 5 due out by the end of the month, I wanted to check if this is going to be updated for the new version.

**Comment by CreateSean** [comment]
Plus one on this.

**Comment by michaelrog** [comment]
On the way!

**Comment by CreateSean** [comment]
Awesome, Thank you.

**Comment by michaelrog** [comment]
Environment Label 5.0.0 is out now with support for Craft 5! 🚀

**Comment by michaeldavidtodd** [comment]
Thank you!
