### ISSUE TITLE
Cannot hide label using dot-env

### ISSUE THREAD

**Issue by davist11** [TopShelfCraft/Environment-Label#3]
My config file looks like:

```
<?php

return [
    'showLabel' => getenv('CRAFT_ENV_SHOW_LABEL'),
    'labelText' => getenv('CRAFT_ENV_LABEL_TEXT'),
];
```

I have this in my `.env`:

```
CRAFT_ENV_SHOW_LABEL="false"
```

PHP sees that as a string, so in the conditional, it's always passing this condition:

```
if (
        EnvironmentLabel::$plugin->getSettings()->showLabel
```

**Comment by michaelrog** [comment]
You can set up [boolean casting](https://github.com/vlucas/phpdotenv#boolean-variables) for specified variables when you instantiate _dotenv_.
```
$dotenv->required('FOO')->isBoolean();
```

You could also use PHP's [`filter_var`](https://stackoverflow.com/a/10645030/4526443) method in your config file.
```
$showLabel = filter_var( getenv('CRAFT_ENV_SHOW_LABEL'), FILTER_VALIDATE_BOOLEAN );
```

Sometimes I even take the lazy route and just use `1` or an empty value to represent booleans:
```
CRAFT_ENV_SHOW_LABEL=1

 #  or...

CRAFT_ENV_SHOW_LABEL=
```

**Comment by davist11** [comment]
Ah nice, thanks
