### ISSUE TITLE
Hide from user group

### ISSUE THREAD

**Issue by CreateSean** [TopShelfCraft/Environment-Label#7]
I'd like to be able to hide the environment label from specific user groups.

**Comment by michaelrog** [comment]
I suspect this is possible using the existing config setup. Try this in your `environment-label.php` config file:

```php
<?php
use Craft;

$currentUser = Craft::$app->getUser()->getIdentity();
$showLabel = $currentUser && $currentUser->isInGroup('specialPeople');

return [
	'showLabel' => $showLabel,
];
```

**Comment by CreateSean** [comment]
I tried that but it doesn't display for anyone.

I want it to show only to superAdmins (me)

I currently have this where I tried setting the group to `admin` and `admins` but no luck.:

```
$currentUser = Craft::$app->getUser()->getIdentity();
$showLabel = $currentUser && $currentUser->isInGroup('admin');

return [
	'showLabel' => $showLabel,
];
```

**Comment by michaelrog** [comment]
@CreateSean — `'admins'` probably doesn't exist as a User Group, unless you have explicitly created it as such. Out of the box, Craft treats system admins as a special-case flag.

Try using the User object's [`isAdmin`](https://docs.craftcms.com/api/v3/craft-web-user.html#isadmin) property (or [`getIsAdmin`](https://docs.craftcms.com/api/v3/craft-web-user.html#getisadmin) method) to determine whether a User is a system admin.
