### ISSUE TITLE
Update label CSS selector for Craft 3.4 compatibility

### ISSUE THREAD

**Issue by ghost** [TopShelfCraft/Environment-Label#8]
This should be updated to `#global-header:before` for use in version 3.4.0 (and up)

https://github.com/TopShelfCraft/Environment-Label/blob/3c719c6844201830c08cdd3d8c438c5050351c9c/src/services/Label.php#L94

Better should be moving this to the config (like your comment suggests), or doing something like this;

```php
return version_compare(
    strtolower(Craft::$app->getInfo()->version), '3.4.0-beta.1', '>='
) ? "#global-header:before" : "#main-container:before";
```

**Comment by michaelrog** [comment]
Thanks @renzo-s!
