### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by peteeveleigh** [TopShelfCraft/Environment-Label#9]
Is there a plan to ensure this plugin is Craft 4 compatible?

**Comment by CreateSean** [comment]
Would really like to see this available for Craft 4 as well.

**Comment by michaelrog** [comment]
I tagged [4.0.0-beta.1](https://github.com/TopShelfCraft/Environment-Label/releases/tag/4.0.0-beta.1) a couple weeks ago. Let me know if you run into any issues!

**Comment by michaelrog** [comment]
Went ahead and tagged `4.0.0` — happy Crafting! 🎉

**Comment by peteeveleigh** [comment]
Woohoo! Thank you :)
